name: tada_messenger
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  formz: 0.4.0-nullsafety.0
  flutter_bloc: 7.0.0
  equatable: 2.0.0
  uuid: 3.0.1
  http: 0.13.0
  get_it: 6.0.0
  bubble: 1.2.1
  cupertino_icons: 1.0.2
  intl: 0.17.0
  keyboard_attachable: 2.0.0
  dartz: 0.10.0-nullsafety.1
  modal_bottom_sheet: 2.0.0
  shared_preferences: 2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: 8.0.0
  mocktail: any

flutter:
  uses-material-design: true

fonts:
  - family: SF Pro Text
    fonts:
      - asset: fonts/SF-Pro-Text-Ultralight.otf
        weight: 100
      - asset: fonts/SF-Pro-Text-Thin.otf
        weight: 200
      - asset: fonts/SF-Pro-Text-Light.otf
        weight: 300
      - asset: fonts/SF-Pro-Text-Regular.otf
        weight: 400
      - asset: fonts/SF-Pro-Text-Medium.otf
        weight: 500
      - asset: fonts/SF-Pro-Text-Semibold.otf
        weight: 600
      - asset: fonts/SF-Pro-Text-Bold.otf
        weight: 700
      - asset: fonts/SF-Pro-Text-Heavy.otf
        weight: 800
      - asset: fonts/SF-Pro-Text-Black.otf